### ISSUE TITLE
运行faiss example失败，提示Error: Can not import paddle core while this file exists: /home/***/.conda/envs/RocketQA/lib/python3.10/site-packages/paddle/fluid/libpaddle.so

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/RocketQA#114]
有解决方案么？
报错信息如下：
Error: Can not import paddle core while this file exists: /home/***/.conda/envs/RocketQA/lib/python3.10/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/mnt/sdb/***/master/RocketQA/examples/faiss_example/index.py", line 5, in <module>
    import rocketqa
  File "/home/***/.conda/envs/RocketQA/lib/python3.10/site-packages/rocketqa/__init__.py", line 17, in <module>
    from .rocketqa import load_model
  File "/home/***/.conda/envs/RocketQA/lib/python3.10/site-packages/rocketqa/rocketqa.py", line 4, in <module>
    import paddle
  File "/home/***/.conda/envs/RocketQA/lib/python3.10/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/home/***/.conda/envs/RocketQA/lib/python3.10/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/***/.conda/envs/RocketQA/lib/python3.10/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/home/***/.conda/envs/RocketQA/lib/python3.10/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/***/.conda/envs/RocketQA/lib/python3.10/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/***/.conda/envs/RocketQA/lib/python3.10/site-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/home/***/.conda/envs/RocketQA/lib/python3.10/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

系统环境是：
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

cuda: 12.2

python环境是：
Package          Version
---------------- -------------
anyio            3.7.1
astor            0.8.1
certifi          2023.7.22
decorator        5.1.1
exceptiongroup   1.1.3
faiss-cpu        1.7.4
h11              0.14.0
httpcore         0.17.3
httpx            0.24.1
idna             3.4
numpy            1.25.2
opt-einsum       3.3.0
paddle-bfloat    0.1.7
paddlepaddle-gpu 2.5.1.post120
Pillow           10.0.0
pip              23.2.1
protobuf         4.24.0
rocketqa         1.1.0
setuptools       68.0.0
sniffio          1.3.0
tornado          6.3.3
tqdm             4.66.1
wheel            0.38.4

**Comment by wencan** [comment]
同样的问题
