### ISSUE TITLE
数据量大一点就报错

### ISSUE THREAD

**Issue by whuter** [PaddlePaddle/RocketQA#23]
使用 jina_example 运行 python app.py index news.tsv
文件读取完后报错：
 du_encoder@21112[E]:IndexError('list index out of range')
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "D:\Program Files\Python3\lib\site-packages\jina\peapods\runtimes\zmq\zed.py", line 285, in _msg_callback
    processed_msg = self._callback(msg)
  File "D:\Program Files\Python3\lib\site-packages\jina\peapods\runtimes\zmq\zed.py", line 271, in _callback
    msg = self._post_hook(self._handle(self._pre_hook(msg)))
  File "D:\Program Files\Python3\lib\site-packages\jina\peapods\runtimes\zmq\zed.py", line 226, in _handle
    peapod_name=self.name,
  File "D:\Program Files\Python3\lib\site-packages\jina\peapods\runtimes\request_handlers\data_request_handler.py", line 165, in handle
    field='groundtruths',
  File "D:\Program Files\Python3\lib\site-packages\jina\executors\__init__.py", line 196, in __call__
    self, **kwargs
  File "D:\Program Files\Python3\lib\site-packages\jina\executors\decorators.py", line 105, in arg_wrapper
    return fn(*args, **kwargs)
  File "D:\Downloads\RocketQA-main\examples\jina_example\rocketqa_encoder\executor.py", line 31, in encode_passage
    para_embs = self.encoder.encode_para(para=paras, title=titles)
  File "D:\Program Files\Python3\lib\site-packages\rocketqa\predict\dual_encoder.py", line 169, in encode_para
    shuffle=False))
  File "D:\Program Files\Python3\lib\site-packages\rocketqa\reader\reader_de_predict.py", line 297, in data_generator
    examples = self._read_samples(samples)
  File "D:\Program Files\Python3\lib\site-packages\rocketqa\reader\reader_de_predict.py", line 283, in _read_samples
    line.append(sample[i])
IndexError: list index out of range

**Comment by whuter** [comment]
应该是某篇文章有问题，谢谢
