### ISSUE TITLE
Running with FAISS got a bug

### ISSUE THREAD

**Issue by ucas010** [PaddlePaddle/RocketQA#85]
python3 index.py zh ../data/dureader.para test_index
RocketQA model [zh_dureader_de_v2]
Download RocketQA model [zh_dureader_de_v2]
100%|███████████████████████████████████████| 693M/693M [00:18<00:00, 38.6MiB/s]
[Errno 28] No space left on device
Traceback (most recent call last):
  File "/data/RocketQA/examples/faiss_example/index.py", line 52, in <module>
    build_index(de_conf, index_file, title_list, para_list)
  File "/data/RocketQA/examples/faiss_example/index.py", line 10, in build_index
    dual_encoder = rocketqa.load_model(**encoder_conf)
  File "/data/envs/xuuie/lib/python3.9/site-packages/rocketqa/rocketqa.py", line 80, in load_model
    raise Exception(f"RocketQA model [{model_name}] download failed, \
Exception: RocketQA model [zh_dureader_de_v2] download failed,                         please check model dir [/root/.rocketqa/zh_dureader_de_v2/]
再次执行
faiss_example]# python3 index.py zh ../data/dureader.para test_index
RocketQA model [zh_dureader_de_v2]
Traceback (most recent call last):
  File "/data/envs/xuuie/lib/python3.9/site-packages/rocketqa/model/ernie.py", line 38, in _parse
    with open(config_path, 'r', encoding='utf8') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.rocketqa/zh_dureader_de_v2/zh_config.json'

could you pls help me ?
thx

**Comment by ylf-Ng** [comment]
"zh_config.json" was unsuccessfully downloaded due to "No space left on device"
